checklist_backend/config/routes.rb
Rails.application.routes.draw do
  resources :user_tasks
  resources :task_categories
  resources :categories
  resources :comments
  resources :tasks
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :tasks, except: [:new, :edit] 
  resources :categories, except: [:new, :edit]
  resources :users, only: [:create, :update, :delete]
  resources :user_tasks, only: [:create, :delete]
  post '/tasks/:id/share', to: 'tasks#share'
  post '/users/user', to: 'users_user#get_user'
  post '/auth', to: 'auth#login'
end

checklist_backend/app/views/shared_tasks/_form.html.erb
<%= form_with(model: user_task) do |form| %>
  <% if user_task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_task.errors.count, "error") %> prohibited this user_task from being saved:</h2>

      <ul>
        <% user_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

checklist_backend/app/views/shared_tasks/_shared_task.html.erb
<div id="<%= dom_id user_task %>">
  <p>
    <strong>Task:</strong>
    <%= user_task.task_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_task.user_id %>
  </p>

</div>

checklist_backend/app/views/shared_tasks/edit.html.erb
<h1>Editing user task</h1>

<%= render "form", user_task: @user_task %>

<br>

<div>
  <%= link_to "Show this user task", @user_task %> |
  <%= link_to "Back to user tasks", user_tasks_path %>
</div>

checklist_backend/app/views/shared_tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User tasks</h1>

<div id="user_tasks">
  <% @user_tasks.each do |user_task| %>
    <%= render user_task %>
    <p>
      <%= link_to "Show this user task", user_task %>
    </p>
  <% end %>
</div>

<%= link_to "New user task", new_user_task_path %>

checklist_backend/app/views/shared_tasks/new.html.erb
<h1>New user task</h1>

<%= render "form", user_task: @user_task %>

<br>

<div>
  <%= link_to "Back to user tasks", user_tasks_path %>
</div>

checklist_backend/app/views/shared_tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_task %>

<div>
  <%= link_to "Edit this user task", edit_user_task_path(@user_task) %> |
  <%= link_to "Back to user tasks", user_tasks_path %>

  <%= button_to "Destroy this user task", @user_task, method: :delete %>
</div>